name: gitlab
# Increasing this version number *automatically* publishes this package
# when merged into master.
version: 0.7.0
description: A library to communicate with the GitLab API
homepage: https://gitlab.com/exitlive/gitlab-dart
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  intl: ^0.17.0
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  test: ^1.18.2
  path: ^1.8.0
  grinder: ^0.9.0
  mocktail: ^0.1.4
