name: gitlab
# Increasing this version number *automatically* publishes this package
# when merged into master.
version: 0.6.0
description: A library to communicate with the GitLab API
homepage: https://gitlab.com/exitlive/gitlab-dart
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  http: ^0.13.3
  logging: ^1.0.2
  intl: ^0.17.0
  meta: ^1.7.0
dev_dependencies:
  test: ^1.18.2
  path: ^1.8.0
  grinder: ^0.9.0
  mocktail: ^0.1.4
